---

  reference:
    coverage_bed:
      checksum: 1f78f4cff1a9bc6a3c654229eb7e843c
      path: hastings/refseq_select_mane_20230828.bed
      type: file
      url: file:/beegfs-storage/data/ref_data/refseq/refseq_select_mane_20230828.bed
    design_bed:
      checksum: f8a920a0983b7fe9998be30d5ee18810
      path: hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed
      type: file
      url: file:/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed
    design_intervals:
      checksum: bd61ce7c4d8a7ed0fc528672f86943a8
      path: hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list
      type: file
      url: file:/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list
    gene_panels:
      checksum: 058349ddd08ef53a0179e0ddafa94636
      path: hastings/genepanels.list
      type: file
      url: file:/beegfs-storage/projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/genepanels.list

  padded_regions:
    checksum: 1e4a414eac6c0da831afa475d97e9aae
    path: hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed
    type: file
    url: file:/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed

