site_name: hastings_rd_wes
nav:
  - Overview:
    - Introduction: index.md
    - Pipeline overview: overview.md
    - Result files: results_files.md
    - Pipeline setup and configuration: setup.md
    - Reference files: references.md
  - Setting up and Running the pipeline:
    - Setup: setup.md
    - Running: running.md
  - Pipeline specific rules:
    - Rule list: softwares.md
  - Output- Project Info:
    - Changelog: changelog.md
    - Credits: credits.md
    - License: license.md
  

theme:
    name: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - mdx_spanner
  - pymdownx.blocks.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: "docs/"
      url_download: "True"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True

