---


resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

output: "config/output_list.json"

default_container: "docker://hydragenetics/common:1.11.1"

modules:
  alignment: "v0.6.0"
  annotation: "v1.1.0"
  compression: "v2.0.0" 
  cnv_sv: "6739845"
  filtering: "v1.1.0"
  misc: "v0.2.0"
  parabricks: "v1.2.1"
  prealignment: "v1.2.0"
  qc: "v0.5.0"
  references: "e71ee62"
  snv_indels: "mosaicforecast"

reference:
  annovar: "/opt/ohpc/pub/annotators/annovar/2025Feb18"
  coverage_bed: "/beegfs-storage/data/ref_data/refseq/hastings_coverage_20250109.bed"
  design_bed: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed"
  design_intervals: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list"
  fasta: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta"
  fai: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai"
  genepanels: "/beegfs-storage/projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/genepanels.list"
  sites: "/data/ref_data/wp3/hastings/Homo_sapiens_assembly38.known_indels.vcf.gz"
  skip_chrs:
    - chrM

trimmer_software: "fastp_pe"

aligner: "bwa_cpu" # or "bwa_cpu"
snp_caller: "deepvariant_cpu" # or "deepvariant_cpu"

automap:
  container: "docker://hydragenetics/automap:1.2"
  build: "hg38"
  extra: "--DP 10 --minsize 3 --chrX"
  outdir: "cnv_sv/automap"

bcftools_view_deepsomatic:
  extra: " -f PASS --exclude 'FORMAT/DP<10 | FORMAT/GQ<20 | FORMAT/VAF>0.4 && FORMAT/VAF<0.6 | FORMAT/VAF<0.02 | FORMAT/VAF>0.98' " # remove gnomad of some AF threshold? -T ^/projects/wp3/nobackup/Workspace/mosaic/hardregNgnomad_hg38.bed

bcftools_view_deepvariant:
  regions: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed"

bwa_mem:
  container: "docker://hydragenetics/bwa:0.7.15"
  amb: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb"
  ann: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann"
  bwt: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt"
  pac: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac"
  sa: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa"
  extra: "-K 100000000"

create_cov_excel:
  covLimits: "10 20 30"

deepmosaic_draw:
  container: "library://sanglee8888/deepmosaic/deepmosaic:sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e"

deepmosaic_predict:
  container: "library://sanglee8888/deepmosaic/deepmosaic:sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e"

deepvariant:
  container: "docker://google/deepvariant:1.6.1" 
  bed: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed"
  model_type: "WES"
  output_gvcf: True

deepsomatic_t_only:
  container: "docker://google/deepsomatic:1.8.0"
  extra: "--use_default_pon_filtering=true " #--use_default_pon_filtering=true or --pon_filtering="pon.vcf" --process_somatic=true or ""
  model: "WGS_TUMOR_ONLY" # WGS,WES,PACBIO,ONT,FFPE_WGS,FFPE_WES,WGS_TUMOR_ONLY,PACBIO_TUMOR_ONLY,ONT_TUMOR_ONLY

exomedepth_call:
  container: "docker://hydragenetics/exomedepth:1.1.15"
  bedfile: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed" 
  exonsfile: "/data/ref_data/wp3/hastings/exons_GRCh38_ensembl109.txt"
  genesfile: "/data/ref_data/wp3/hastings/genes_GRCh38_ensembl109.txt"
  genome_version: "hg38"

exomedepth_export:
  container: "docker://hydragenetics/exomedepth:1.1.15"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"
  # Default enabled trimming parameters for fastp. Specified for clarity.
  extra: "--trim_poly_g --qualified_quality_phred 15 --unqualified_percent_limit 40 --n_base_limit 5 --length_required 15"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

glnexus_peddy:
  container: "docker://ghcr.io/dnanexus-rnd/glnexus:v1.4.1"
  configfile: "DeepVariantWES"

glnexus_trio:
  container: "docker://ghcr.io/dnanexus-rnd/glnexus:v1.4.1"
  configfile: "DeepVariantWES"

melt:
  container: "docker://vanallenlab/melt:3159ce1"
  bed: "/projects/wp3/Software/MELTv2.2.2/add_bed_files/Hg38/Hg38.genes.bed"
  extra: ""
  mei: "/projects/wp3/Software/MELTv2.2.2/mei_list.txt"

mosaicforecast:
  container: "docker://yanmei/mosaicforecast_hg38:0.0.1"
  path: "alignment/samtools_merge_bam/"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: ""

multiqc:
  container: "docker://hydragenetics/multiqc:1.21"
  reports:
    DNA:
      config: "config/multiqc_config_DNA.yaml"
      included_unit_types: ["N"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/peddy/peddy.peddy.ped"
        - "qc/peddy/peddy.background_pca.json"
        - "qc/peddy/peddy.ped_check.csv"
        - "qc/peddy/peddy.sex_check.csv"
        - "qc/peddy/peddy.het_check.csv"
        - "qc/peddy/peddy_sex_check_mqc.tsv"
        - "qc/peddy/peddy_rel_check_mqc.tsv"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt"

pbrun_deepvariant:
  container: "docker://nvcr.io/nvidia/clara/clara-parabricks:4.3.1-1"
  extra: "--use-wes-model --mode shortread \
   --disable-use-window-selector-model --gvcf " ## disable window selector model for consistency with deepvariant cpu. Also increases accuracy.

pbrun_fq2bam:
  container: "docker://nvcr.io/nvidia/clara/clara-parabricks:4.3.1-1"
  extra: ""

peddy:
  container: "docker://hydragenetics/peddy:0.4.8"
  config: "config/peddy_mqc.yaml"
  extra: "--sites hg38 "

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_wgs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.4"

spring:
  container: "docker://hydragenetics/spring:1.1.1"

upd:
  container: "docker://hydragenetics/upd:0.1.1"
  extra: "--vep "

vep_trio:
  container: "docker://ensemblorg/ensembl-vep:release_110.1"
  vep_cache: "/beegfs-storage/data/ref_genomes/VEP/"
  extra: "--assembly GRCh38 --check_existing --pick --max_af "

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"
