exomedepth_call:
  male_reference: "/data/ref_data/wp3/hastings/Twist2.0_hg38_RefCount_male_nextseq.Rdata" 
  female_reference: "/data/ref_data/wp3/hastings/Twist2.0_hg38_RefCount_female_nextseq.Rdata"