REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp3_te/design_and_ref_files
APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp3_te/apptainer_cache

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp3_te/hastings_rd_wes_{{PIPELINE_VERSION}}/hydra-genetics

resources: config/resources.miarka.yaml


reference:
  coverage_bed: '{{REFERENCE_DATA}}/hastings/hastings_coverage_20250109.bed'
  design_bed: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed'
  design_intervals: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list'
  fai: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai'
  fasta: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta'
  genepanels: '{{REFERENCE_DATA}}/hastings/genepanels.list'
  sites: '{{REFERENCE_DATA}}/hastings/Homo_sapiens_assembly38.known_indels.vcf.gz'
  skip_chrs:
  - chrM

bcftools_view_deepvariant:
  regions: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed'

bwa_mem:
  amb: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb'
  ann: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann'
  bwt: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt'
  pac: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac'
  sa: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa'

deepvariant:
  bed: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed'

exomedepth_call:
  bedfile: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed'
  exonsfile: '{{REFERENCE_DATA}}/hastings/exons_GRCh38_ensembl109.txt'
  genesfile: '{{REFERENCE_DATA}}/hastings/genes_GRCh38_ensembl109.txt'

melt:
  bed: "{{REFERENCE_DATA}}/hastings/melt/Hg38.genes.bed"
  mei: "{{REFERENCE_DATA}}/hastings/melt/mei_list.txt"