---



reference:
  design_bed: "{{ref_comp_design_bed}}"
  design_intervals: "{{ref_comp_design_intervals}}"

bcftools_view_deepvariant:
  regions: "{{ref_comp_design_bed_padded}}"

deepvariant:
  bed: "{{ref_comp_design_bed_padded}}"

exomedepth_call:
  bedfile: "{{ref_comp_exomedepth_bed}}"
  male_reference: "{{ref_comp_exomedepth_pon_male}}"
  female_reference: "{{ref_comp_exomedepth_pon_female}}"








