---

samples: "config/samples_ref.tsv"
units: "config/units_ref.tsv"

output: "config/output_files_ref.yaml"


exomedepth_reference:
  container: "{{CONTAINER_DIR}}/hydragenetics__exomedepth_1.1.15.sif"