---

samples: "config/samples.tsv"
units: "config/units.tsv"

output: "config/output_files.yaml"

default_container: "{{CONTAINER_DIR}}/hydragenetics__common_1.11.1.sif"

modules:
  alignment: "v0.6.0"
  annotation: "v0.3.0"
  compression: "v2.0.0" 
  cnv_sv: "v3.2.1"
  filtering: "v1.1.0"
  misc: "v0.2.0"
  parabricks: "v1.1.0"
  prealignment: "v1.2.0"
  qc: "v0.8.0"
  references: "v1.0.1"
  snv_indels: "v1.0.0"

reference:
  coverage_bed: "{{ref_coverage_bed}}"
  design_bed: "{{ref_design_bed}}"
  design_intervals: "{{ref_design_intervals}}"
  fasta: "{{ref_fasta}}"
  fai: "{{ref_fai}}"
  genepanels: "{{ref_genepanels}}"
  sites: "{{ref_known_indels}}"
  skip_chrs:
    - chrM

trimmer_software: "fastp_pe"

automap:
  container: "{{CONTAINER_DIR}}/hydragenetics__automap_1.2.sif"
  build: "hg38"
  extra: "--DP 10 --minsize 3 --chrX"
  outdir: "cnv_sv/automap"

bcftools_view_deepvariant:
  regions: "{{ref_design_bed_padded}}"

bcftools_hardfilter_exomedepth:
  exclude: "'BF<=0'"

bcftools_softfilter_melt:
  exclude: "'FILTER~\"ac0\" '"
  extra: "-s LowQual "

bcftools_softfilter_scramble:
  exclude: "'INFO/Clipped_Reads_In_Cluster<5 || INFO/Alignment_Score<60 || INFO/Alignment_Percent_Length<90 || INFO/Alignment_Percent_Identity<90'"
  extra: "-s LowQual "

bcftools_view_svdb:
  extra: "-e 'FILTER~\"LowQual\"'"

bwa_mem:
  container: "{{CONTAINER_DIR}}/hydragenetics__bwa_0.7.15.sif"
  amb: "{{ref_bwa_amb}}"
  ann: "{{ref_bwa_ann}}"
  bwt: "{{ref_bwa_bwt}}"
  pac: "{{ref_bwa_pac}}"
  sa: "{{ref_bwa_sa}}"
  extra: "-K 100000000"

create_cov_excel:
  covLimits: "10 20 30"

deepvariant:
  container: "{{CONTAINER_DIR}}/google__deepvariant_1.6.1.sif" 
  bed: "{{ref_design_bed_padded}}"
  model_type: "WES"
  output_gvcf: True
  
exomedepth_call:
  container: "{{CONTAINER_DIR}}/hydragenetics__exomedepth_1.1.15.sif"
  bedfile: "{{ref_design_bed}}" 
  exonsfile: "{{ref_exons}}"
  genesfile: "{{ref_genes}}"
  genome_version: "hg38"

exomedepth_export:
  container: "{{CONTAINER_DIR}}/hydragenetics__exomedepth_1.1.15.sif"

fastp_pe:
  container: "{{CONTAINER_DIR}}/hydragenetics__fastp_0.20.1.sif"
  # Default enabled trimming parameters for fastp. Specified for clarity.
  extra: "--trim_poly_g --qualified_quality_phred 15 --unqualified_percent_limit 40 --n_base_limit 5 --length_required 15"

fastqc:
  container: "{{CONTAINER_DIR}}/hydragenetics__fastqc_0.11.9.sif"

glnexus_peddy:
  container: "{{CONTAINER_DIR}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif"
  configfile: "DeepVariantWES"

glnexus_trio:
  container: "{{CONTAINER_DIR}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif"
  configfile: "DeepVariantWES"

melt:
  container: "{{CONTAINER_DIR}}/MELT_v2.2.2.sif"
  bed: "{{ref_melt_bed}}"
  extra: "-r 150 -exome"
  mei: "{{ref_melt_mei}}"

mosdepth_bed:
  container: "{{CONTAINER_DIR}}/hydragenetics__mosdepth_0.3.2.sif"
  extra: ""

multiqc:
  container: "{{CONTAINER_DIR}}/hydragenetics__multiqc_1.21.sif"
  reports:
    DNA:
      config: "config/multiqc_config_DNA.yaml"
      included_unit_types: ["N"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed_design/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/peddy/peddy.peddy.ped"
        - "qc/peddy/peddy.background_pca.json"
        - "qc/peddy/peddy.ped_check.csv"
        - "qc/peddy/peddy.sex_check.csv"
        - "qc/peddy/peddy.het_check.csv"
        - "qc/peddy/peddy_sex_check_mqc.tsv"
        - "qc/peddy/peddy_rel_check_mqc.tsv"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt"

pbrun_deepvariant:
  container: "{{CONTAINER_DIR}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.1-1.sif"
  extra: "--use-wes-model --mode shortread \
   --disable-use-window-selector-model --gvcf " ## disable window selector model for consistency with deepvariant cpu. Also increases accuracy.

pbrun_fq2bam:
  container: "{{CONTAINER_DIR}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.1-1.sif"
  extra: ""

peddy:
  container: "{{CONTAINER_DIR}}/hydragenetics__peddy_0.4.8.sif"
  config: "config/peddy_mqc.yaml"
  extra: "--sites hg38 "

picard_collect_alignment_summary_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_duplication_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_gc_bias_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_hs_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_insert_size_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_multiple_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_collect_wgs_metrics:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.0.sif"

picard_mark_duplicates:
  container: "{{CONTAINER_DIR}}/hydragenetics__picard_2.25.4.sif"

samtools_merge_bam:
  extra: "-c -p"

scramble_cluster_analysis:
  container: "{{CONTAINER_DIR}}/hydragenetics__scramble_1.0.2.sif"
  mei_refs: "/opt/scramble/cluster_analysis/resources/MEI_consensus_seqs.fa" # path in the container
  install_dir: "/opt/scramble/cluster_analysis/bin" # path in the container

scramble_cluster_identifier:
  container: "{{CONTAINER_DIR}}/hydragenetics__scramble_1.0.2.sif"

svdb_merge:
  container: "{{CONTAINER_DIR}}/hydragenetics__svdb_2.10.2.sif"
  overlap: 0.6
  priority: "exomedepth,melt,scramble"
  extra: "--pass_only --no_intra "

upd:
  container: "{{CONTAINER_DIR}}/hydragenetics__upd_0.1.1.sif"
  extra: "--vep "

vep_trio:
  container: "{{CONTAINER_DIR}}/ensemblorg__ensembl-vep_release_110.1.sif"
  vep_cache: "{{ref_vep_cache}}"
  extra: "--assembly GRCh38 --check_existing --pick --max_af "

vt_decompose:
  container: "{{CONTAINER_DIR}}/hydragenetics__vt_2015.11.10.sif"
