---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "low"

bwa_mem:
  mem_mb: 122880
  mem_per_cpu: 6144
  threads: 20

deeptrio_call_variants:
  gres: "--gres=gpu:1"
  partition: "GPU"
  threads: 10

deeptrio_make_examples:
  threads: 1

deeptrio_postprocess_variants:
  mem_mb: 36864
  mem_per_cpu: 36864

deepvariant_call_variants:
  threads: 20

deepvariant_make_examples:
  threads: 1

deepvariant_postprocess_variants:
  mem_mb: 36864
  mem_per_cpu: 36864

fastp_pe:
  threads: 5
  mem_mb: 30720
  mem_per_cpu: 6144

fastqc:
  threads: 2
  mem_mb: 12288
  mem_per_cpu: 6144

glnexus:
  threads: 20

mosdepth_bed:
  mem_mb: 36864
  threads: 4

pbrun_fq2bam:
  gres: "--gres=gpu:2"
  mem_mb: 327680
  mem_per_cpu: 16384
  partition: "GPU"
  threads: 20
  time: "20:00:00"

# pbrun_fq2bam:
#   gres: "--gres=gpu:2"
#   mem_mb: 327680
#   mem_per_cpu: 16384
#   partition: "GPU"
#   threads: 20
#   time: "20:00:00"

pbrun_deepvariant:
  gres: "--gres=gpu:2"
  mem_mb: 327680
  mem_per_cpu: 16384
  partition: "GPU"
  threads: 20
  time: "20:00:00"

peddy:
  threads: 8

samtools_sort:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

samtools_view:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

spring:
  mem_mb: 368640
  threads: 8

vep:
  threads: 4