---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "core"

bwa_mem:
  mem_mb: 122880
  mem_per_cpu: 6144
  threads: 8

deepvariant:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10
  time: "12:00:00"

fastp_pe:
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

fastqc:
  threads: 2
  mem_mb: 12288
  mem_per_cpu: 6144

glnexus:
  threads: 20

mosdepth_bed:
  mem_mb: 36864
  threads: 4

pbrun_fq2bam:
  gres: "--gres=gres:gpu:2"
  mem_mb: 327680
  mem_per_cpu: 16384
  partition: "GPU_hi"
  threads: 20

pbrun_deepvariant:
  gres: "--gres=gres:gpu:4"
  mem_mb: 655360
  mem_per_cpu: 16384
  partition: "GPU_hi"
  threads: 40

peddy:
  threads: 8

samtools_sort:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

samtools_view:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

spring:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8
  partition: "core_bkup"

vep:
  threads: 4