# Marvin site override following the standard config/site layout.

PIPELINE_HOME: /projects/bin/wp3_te/hastings_rd_wes/{{PIPELINE_VERSION}}
REFERENCE_DATA_DIR: /projects/cgu/library/references/GRCh38
CONTAINER_DIR: /projects/wp4/nobackup/singularity_cache
HYDRA_MODULES_DIR: /projects/bin/wp3_te/hastings_rd_wes/{{PIPELINE_VERSION}}/hydra-genetics
RESOURCES_FILE: config/resources.yaml
PACKAGED_REF_DIR: /data/ref_data/wp3/hastings

resources: "{{RESOURCES_FILE}}"
hydra_local_path: "{{HYDRA_MODULES_DIR}}"

reference:
  coverage_bed: "/beegfs-storage/data/ref_data/refseq/hastings_coverage_20250109.bed"
  design_bed: "{{PACKAGED_REF_DIR}}/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed"
  design_intervals: "{{PACKAGED_REF_DIR}}/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list"
  fasta: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta"
  fai: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai"
  genepanels: "/beegfs-storage/projects/wp3/Reference_files/Manifest/Clinical_research_exome/Gene_panels/genepanels.list"
  sites: "{{PACKAGED_REF_DIR}}/Homo_sapiens_assembly38.known_indels.vcf.gz"
  skip_chrs:
    - chrM

bcftools_view_deepvariant:
  regions: "{{PACKAGED_REF_DIR}}/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed"

bwa_mem:
  amb: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb"
  ann: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann"
  bwt: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt"
  pac: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac"
  sa: "{{PACKAGED_REF_DIR}}/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa"

deepvariant:
  bed: "{{PACKAGED_REF_DIR}}/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed"

exomedepth_call:
  bedfile: "{{PACKAGED_REF_DIR}}/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed"
  exonsfile: "{{PACKAGED_REF_DIR}}/exons_GRCh38_ensembl109.txt"
  genesfile: "{{PACKAGED_REF_DIR}}/genes_GRCh38_ensembl109.txt"

vep_trio:
  vep_cache: "/beegfs-storage/data/ref_genomes/VEP/"
