---
# ---------------------------------------------------------------------------
#  Site-config - Miarka
#
#  Anvands som: --configfile config/site_configs/site_config_miarka.yaml
# ---------------------------------------------------------------------------

APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp3_te/apptainer_cache
# Containerbiblioteket. Fylls av tools/build_containers.sh vid installation.
CONTAINER_DIR: /proj/ngi2024001/nobackup/cgu/library/containers

resources: "config/resources/resources_miarka.yaml"

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp3_te/hastings_rd_wes_{{PIPELINE_VERSION}}/hydra-genetics

